name: 'my_dbt_project'
version: '1.0'
profile: 'default'
source-paths: ["models"]
target-path: "target"
clean-targets: ["target"]
version: "1"
context:
  active-host: "nl214.us1.dbt.com"
  active-project: "70471823418738"
projects:
  - project-name: "Analytics"
    project-id: "70471823418738"
    account-name: "Pomoc "
    account-id: "70471823416086"
    account-host: "nl214.us1.dbt.com"
    token-name: "cloud-cli-753a"
    token-value: "dbtu_TY-VB3kHdYX_C3zzZw9shn3_f1sZO_e1t8rDMvXgUu-9bQe8Eo"

